<MyLayout>

	BoxLayout:
		size:root.width, root.height
		orientation: 'vertical'
		padding: 10  # espacement entre la fenêtre principale et les widgets
		spacing: 5  # espacement entre widgets

		Label:

			id: my_label
			text: 'Hello World!'
			font_size: 32

		Button:

			text: 'Appuie sur moi!'
			font_size: 32
			size_hint: .5, .5
			pos_hint: {'center_x': .5}

			on_release: root.animate_it(self)